# -*- coding: utf-8 -*-
"""Streamlit.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18XSVrWsupqkwv0S3DQ7AoWoRzoHAAPdk

!pip install streamlit

!pip install colabcode
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import joblib
# 
# model = joblib.load("model.pkl")
# 
# st.title("Spam Detection App")
# 
# comment = st.text_input("Enter a comment:")
# 
# if st.button("Classify"):
#     prediction = model.predict([comment])
#     result = "Spam" if prediction[0] == 1 else "Not Spam"
#     st.write(f"Result: {result}")
# 
#     from colabcode import ColabCode
# ColabCode(port=10000, code=False)